# Model
model_name: "amuvarma/rows-1-5-checkpoint-12000-of-40000"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "amuvarma/rows-1-5-checkpoint-12000-of-40000"

# Training Args
epochs: 1
batch_size: 1
number_processes: 2
pad_token: 128263
save_steps: 12000
learning_rate: 0.0

# Datasets
TTS_dataset: "amuvarma/podcast-snac-mod7-1-5-TTS-8192"

# Naming and paths
save_folder: "checkpoints"
project_name: "EVAL_row1-5-snac"
run_name: "onlyr1-5-shorterrows"
