# Model
model_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493" 
tokenizer_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493"

# Training Args
epochs: 1
batch_size: 1
number_processes: 2
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/voice-actors-13-full-audio3k-24k-notnormalised-dedup-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "1b-8va-tune-fullprec"
run_name: "1b-reg-tune-nowa-5e5-b4"

resize_dataset: false