# Model
model_name: "amuvarma/3b-2m-whisper-proj-vatune"
base_model_name: "amuvarma/zuckconvotune-3b-2m-checkpoint-124"
tokenizer_name: "meta-llama/Llama-3.2-3B"
audio_model_id: "facebook/wav2vec2-base-960h"
audio_processor_id: "facebook/wav2vec2-base-960h"
audio_token_index: 156939
vocab_size: 156939

# Training Args
epochs: 1
batch_size: 1
pad_token: 128263
save_steps: 10000
learning_rate: 2.0e-4
gradient_accumulation_steps: 1

# Datasets
dataset_names: 
  - "amuvarma/zuckqa-with-qaaudio-total-cast-snacced"

# Naming and paths
save_folder: "checkpoints"
project_name: "eval-projector-3b-snactune"
run_name: "eval-proj-3b-2m-checkpoint-proj2-3281"

resize_dataset: false