model_name: "amuvarma/3b-10m-pretrain-full"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 10000
learning_rate: 5.0e-6

# Datasets
# text_QA_dataset: "amuvarma/tagged-qas-extended-proc"
# TTS_dataset: "amuvarma/luna-all-raw-snacced-TTS-2g"

text_QA_dataset: "amuvarma/10k-qa-proc-3g"
TTS_dataset: "amuvarma/2k-luna-tts"
# Naming and paths
save_folder: "checkpoints"
project_name: "luna-convo"
run_name: "r5"

resize_dataset: false