# Model
model_name: "amuvarma/r15-checkpoint-70201"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/comb-enh-clip-snac-mod7-1-5-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "zac-zoe-1_5"
run_name: "5e6-0"

resize_dataset: false