# Model
model_name: "amuvarma/8b-zuckqa-TTTTS"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.1-8B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 2
pad_token: 128263
save_steps: 500
learning_rate: 5.0e-6

# Datasets
text_QA_dataset: "amuvarma/reg-convs-1-2"
TTS_dataset: "amuvarma/reg-convs-2-2"

# Naming and paths
save_folder: "checkpoints"
project_name: "zuck-reg-convo-tune-3b"
run_name: "21-1-8b-r4-lr-5e6"

resize_dataset: false