# Model
model_name: "amuvarma/3b-10m-pretrain-full"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-7

# Datasets
TTS_dataset: "amuvarma/2000-playful-conversations-iids"

# Naming and paths
save_folder: "checkpoints"
project_name: "personality-tune-2k"
run_name: "10m-3b-tts-5e7"

resize_dataset: false