# Model
model_name: "canopylabs/orpheus-tts-0.1-pretrained" 
tokenizer_name: "canopylabs/orpheus-tts-0.1-pretrained"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/voice-actors-13-full-audio-snacced-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "1b-tune"
run_name: "5e6-unproc"

resize_dataset: false