# Model
model_name: "amuvarma/3b-2m-whisper-proj-vatune"
base_model_name: "amuvarma/zuckconvotune-3b-2m-checkpoint-124"
tokenizer_name: "meta-llama/Llama-3.2-3B"
audio_model_id: "facebook/wav2vec2-base-960h"
audio_processor_id: "facebook/wav2vec2-base-960h"
audio_token_index: 156939
vocab_size: 156939

# Training Args
epochs: 1
batch_size: 1
pad_token: 128263
save_steps: 10000
learning_rate: 2.0e-6
gradient_accumulation_steps: 1

# Datasets
dataset_names: 
  - "amuvarma/qa_pairs_regular-sttsed"

# Naming and paths
save_folder: "checkpoints"
project_name: "eval-convo-text"
run_name: "va-tune-llmunfreeze-2e-4-r2"
resize_dataset: false 