model_name: "amuvarma/3b-10m-pretrain-full"
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 10000
learning_rate: 5.0e-6

# Datasets
# text_QA_dataset: "amuvarma/all-tagged-qa-6k-proc-2g"
# TTS_dataset: "amuvarma/luna-all-raw-snacced-TTS-2g"

text_QA_dataset: "amuvarma/tagged-qas-extended-proc"
TTS_dataset: "amuvarma/luna-tags_tts_convos-coll-ttsed-proc"
# Naming and paths
save_folder: "checkpoints"
project_name: "luna-convo"
run_name: "r4"

resize_dataset: false