# Model
model_name: "amuvarma/llama-3b-emilia_retrain-216985-216985"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/brian-48k-KRVv68cDw2PBeOJypLrzaiI4kol2-enhanced-clipped-snacced-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "brian-notags"
run_name: "5e6-0"

resize_dataset: false