# Model
model_name: "amuvarma/8b-2m-pretrain"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-5

# Datasets
TTS_dataset: "amuvarma/plus_2000-playful-conversations"

# Naming and paths
save_folder: "checkpoints"
project_name: "personality-tune-2k"
run_name: "8b-tts-5e6-batch2"

resize_dataset: false