# Model
model_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493" 
tokenizer_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/voice-actors-13-full-audio-snacced-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "zac-135m-all"
run_name: "5e4-0"

resize_dataset: false