model_name: "amuvarma/luna-tts-tags"
tokenizer_name: "meta-llama/Llama-3.1-8B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 2000
learning_rate: 5.0e-6

# Datasets
text_QA_dataset: "amuvarma/lunaconvo-textlabels"
TTS_dataset: "amuvarma/luna-tags_tts_convos-ttsed-proc"
# Naming and paths
save_folder: "checkpoints"
project_name: "luna-convo"
run_name: "r0"

resize_dataset: false