# Model
model_name: "amuvarma/llama-3b-emilia_retrain-216985-216985"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-6

# Datasets
TTS_dataset: "amuvarma/tdt-proc"

# Naming and paths
save_folder: "checkpoints"
project_name: "personality-tune-2k"
run_name: "og-8b-tts-5e6-batch2-1ep"

resize_dataset: true