# Model
model_name: "checkpoints/checkpoint-3102/3281 "
base_model_name: "amuvarma/snac-pretrain-2m-96000"
tokenizer_name: "meta-llama/Llama-3.2-3B"
audio_model_id: "facebook/wav2vec2-base-960h"
audio_processor_id: "facebook/wav2vec2-base-960h"
audio_token_index: 156939
vocab_size: 156939

# Training Args
epochs: 1
batch_size: 4
pad_token: 128263
save_steps: 10000
learning_rate: 2.0e-3
gradient_accumulation_steps: 1

# Datasets
dataset_names: 
  - "amuvarma/va-310k-320k-snac-StTtS"


# Naming and paths
save_folder: "checkpoints"
project_name: "projector-3b"
run_name: "15-1-3b-2m-50kqa-noaud-r1"

resize_dataset: false