# Model
model_name: "amuvarma/135m-tts-pretrain-checkpoint-112806-of-112806" 
tokenizer_name: "HuggingFaceTB/SmolLM2-135M-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 5.0e-4

# Datasets
TTS_dataset: "amuvarma/brian-for-snac-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "zac-135m-all"
run_name: "5e4-0"

resize_dataset: false