# Model
model_name: "HuggingFaceTB/SmolLM2-360M-Instruct" 
tokenizer_name: "HuggingFaceTB/SmolLM2-360M-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 5.0e-3


# Datasets
TTS_dataset: "amuvarma/grouped-smol-8192"

# Naming and paths
save_folder: "checkpoints"
project_name: "360m-TTS"
run_name: "5e3-3-batch1-cont"
