# Model
model_name: "amuvarma/360m-tts-tune-checkpoint-112806-of-112806" 
# model_name: "checkpoints/checkpoint-671"
tokenizer_name: "HuggingFaceTB/SmolLM2-360M-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 1
pad_token: 0
save_steps: 12000
learning_rate: 5.0e-3


# Datasets
TTS_dataset: "amuvarma/tara-codes-smol-dedup-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "400m-tune-dedups"
run_name: "r0-5e4-tara-og"
