# Model
model_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493" 
tokenizer_name: "meta-llama/Llama-3.1-8B-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 5.0e-5


# Datasets
TTS_dataset: "amuvarma/voice-actors-13-full-audio-snacced-TTS"

# Naming and paths
save_folder: "checkpoints"
project_name: "8b-pretrain-debug"
run_name: "r0"
