# Model
model_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493" 
# model_name: "checkpoints/checkpoint-671"
tokenizer_name: "amuvarma/1b-tts-pretrain-checkpoint-108493-of-108493"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 5.0e-6


# Datasets
TTS_dataset: "amuvarma/em-EN-TTS-full-8192"

# Naming and paths
save_folder: "checkpoints"
project_name: "1b-extended-pretrain"
run_name: "r0-5e6"
