# Model
model_name: "meta-llama/Llama-3.2-3B"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B"

# Training Args
epochs: 1
batch_size: 1
number_processes: 24
pad_token: 128263
save_steps: 12000
learning_rate: 5e-5

# Datasets
text_QA_dataset: "amuvarma/text-messages-6m-processed-combined-trunc"
TTS_dataset: "amuvarma/snac-2m-tts-combined"

# Naming and paths
save_folder: "checkpoints"
project_name: "interleaving-datasets-pretrain"
run_name: "10-12-batched-alternating-r3"
