# Model
model_name: "amuvarma/500m-dedup-tts-pret" 
tokenizer_name: "HuggingFaceTB/SmolLM2-360M-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 4
pad_token: 0
save_steps: 12000
learning_rate: 9.0e-4


# Datasets
TTS_dataset: "amuvarma/voice-actors-13-full-audio3k-24k-notnormalised-dedup-smol-TTS-smol"

# Naming and paths
save_folder: "checkpoints"
project_name: "400m-tune-dedups"
run_name: "r0-9e4"
