# Model
model_name: "meta-llama/Llama-3.2-1B-Instruct"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-1B-Instruct"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 5.0e-5
ratio: 6

# Datasets
text_QA_dataset: "amuvarma/text-messages-6m-processed-1-2g-8192l"
TTS_dataset: "amuvarma/emilia-snac-merged-all-TTS-grouped-8192"

# Naming and paths
save_folder: "checkpoints"
project_name: "catfor-ratio-testing-3b"
run_name: "r0-ratio-6"
