# Model
model_name: "canopylabs/orpheus-tts-0.1-pretrained" 
# model_name: "checkpoints/checkpoint-671"
tokenizer_name: "canopylabs/orpheus-tts-0.1-pretrained"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 0.0


# Datasets
TTS_dataset: "amuvarma/multilingual-pretrain_1-8192"

# Naming and paths
save_folder: "checkpoints"
project_name: "multilingual-extended-train"
run_name: "r0-0"
