# Model
model_name: "amuvarma/zuckconvotune-3b-2m-checkpoint-124"
tokenizer_name: "meta-llama/Llama-3.2-3B"
audio_model_id: "facebook/wav2vec2-base-960h"
audio_processor_id: "facebook/wav2vec2-base-960h"
audio_token_index: 156939
vocab_size: 156939

# Training Args
epochs: 1
batch_size: 16
pad_token: 128263
save_steps: 10000
learning_rate: 2.0e-3
gradient_accumulation_steps: 1

# Datasets
dataset_names: 
  # - "amuvarma/mls-eng-10k-500k-projection_prep"
  # - "amuvarma/proj-train-qa-and-speechqa"
  - "amuvarma/va-310k-320k-snac-StTtS"


# Naming and paths
save_folder: "checkpoints"
project_name: "pretrain_projector-3b-deb"
run_name: "16-1-whisper-omni-debug"

resize_dataset: false