# Model
model_name: "google/gemma-2-9b-it"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "google/gemma-2-9b-it"

# Training Args
epochs: 1
batch_size: 1
number_processes: 8
pad_token: 128263
save_steps: 12000
learning_rate: 5.0e-5

# Datasets
TTS_dataset: "amuvarma/emilia-snac-merged-CanopyElias-gemma-TTS-30k-grouped-2048"

# Naming and paths
save_folder: "checkpoints"
project_name: "emilia-gemma-pretrain"
run_name: "r2"
